tools:
  - type: tool
    name: Go v17
    executable: go
    getVersion: go version
    versionRegex: go1\.17\.
    installUrls:
      default: https://go.dev/blog/go1.18beta2
    installOptions:
      apt: sudo apt install golang-1.17.1
      apt-get: sudo install golang-1.17.1
      brew: brew install golang

  - type: tool
    name: NodeJS v14
    executable: node
    getVersion: node --version
    versionRegex: ^v14
    installUrls:
      default: https://go.dev/blog/go1.18beta2
    installOptions:
      apt: sudo apt install golang-1.17.1]
      apt-get: sudo apt-get install golang-1.17.1]
      brew: brew install golang
    changeVersions:
      nvm: nvm use 14

commands:
  - name: Compile executable
    command: [make, make build]

  - name: Run against the repo's doctor.config.yml
    command: make run

  - name: Same as run, but print all debug logs
    command: make debug

  - name: Run against a specific config
    command: go run main.go -c examples/node.yml

  - name: Cleanup the application's dependencies
    command: go mod tidy
