tools:
  - name: Go v17
    executable: go2
    getVersionArgs: [version]
    versionRegex: "go1\\.17\\."
    installUrls:
      default: https://go.dev/blog/go1.18beta2
    installOptions:
      apt: [install, golang-1.17.1]
      apt-get: [install, golang-1.17.1]
      brew: [install, golang]
  - name: NodeJS v14
    executable: node
    getVersionArgs: [--version]
    versionRegex: "^v14"
    installUrls:
      default: https://go.dev/blog/go1.18beta2
    installOptions:
      apt: [install, golang-1.17.1]
      apt-get: [apt-get, install, golang-1.17.1]
      brew: [install, golang]
    changeVersions:
      nvm: [use, "14"]
#
# commands:
#   - name: Compile executable
#     command: [make, make b, make build]
#
#   - name: Run against the repo's doctor.config.yml
#     command: [make r, make run]
#
#   - name: Same as run, but print all debug logs
#     command: [make r, make run]
#
#   - name: Run against a specific config
#     command: go run main.go -c examples/node.yml
#
#   - name: Cleanup the application's dependencies
#     command: go mod tidy
