name: PR Checks
on:
  push:
    branches-ignore:
      - main
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  verify-pr:
    name: Verify PR
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Install Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Run doctor
        run: USE_LOCAL_SCHEMA=true ./bin/doctor --debug
