name: Publish
on:
  workflow_dispatch: {}

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Install Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: make build

      - name: Run doctor
        run: USE_LOCAL_SCHEMA=true ./bin/doctor --debug

  release:
    name: Create Release
    runs-on: ubuntu-20.04
    needs: [verify]
    outputs:
      version: ${{ steps.changelog.outputs.version }}
      new_release_upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Install Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Create Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          output-file: "false"
          fallback-version: "0.1.0"
          version-file: meta.json
          git-user-name: aklinker1
          git-user-email: aaronklinker1@gmail.com

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

  publish:
    name: Publish Binaries
    runs-on: ubuntu-20.04
    needs: [release]
    steps:
      - name: Install Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: make build

      - name: Build Details
        id: build_details
        run: |
          echo "::set-output name=variant::v${{ needs.release.outputs.version }}-$(uname -s)-$(uname -m)"

      - name: Upload To New Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.new_release_upload_url }}
          asset_path: bin/doctor
          asset_name: doctor-${{ steps.build_details.outputs.variant }}
          asset_content_type: application/octet-stream

      - name: Upload To Downloads Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/aklinker1/project-doctor/releases/62689370/assets{?name,label}
          asset_path: bin/doctor
          asset_name: doctor-${{ steps.build_details.outputs.variant }}
          asset_content_type: application/octet-stream
